"""create initial DWH schema

Revision ID: 74a7ea3d9f4f
Revises: 
Create Date: 2026-08-09 15:45:27.033108

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '74a7ea3d9f4f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dim_date',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_date', sa.Date(), nullable=False),
    sa.Column('day', sa.Integer(), nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=False),
    sa.Column('day_name', sa.String(length=16), nullable=False),
    sa.Column('week', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('month_name', sa.String(length=16), nullable=False),
    sa.Column('quarter', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('is_weekend', sa.Boolean(), nullable=False),
    sa.Column('is_holiday', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('full_date')
    )
    op.create_table('dim_parking_lot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_lot_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=False),
    sa.Column('total_capacity', sa.Integer(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_lot_id')
    )
    op.create_table('dim_time',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_time', sa.Time(), nullable=False),
    sa.Column('hour', sa.Integer(), nullable=False),
    sa.Column('minute', sa.Integer(), nullable=False),
    sa.Column('time_of_day', sa.String(length=16), nullable=False),
    sa.Column('is_peak', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('full_time')
    )
    op.create_table('dim_vehicle_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vehicle_type', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vehicle_type')
    )
    op.create_table('dim_parking_slot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_slot_id', sa.Integer(), nullable=False),
    sa.Column('parking_lot_id', sa.Integer(), nullable=False),
    sa.Column('slot_number', sa.String(length=32), nullable=False),
    sa.Column('floor', sa.Integer(), nullable=True),
    sa.Column('zone', sa.String(length=32), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['parking_lot_id'], ['dim_parking_lot.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('parking_lot_id', 'slot_number', name='uq_dwh_slot_lot_number'),
    sa.UniqueConstraint('source_slot_id')
    )
    op.create_index(op.f('ix_dim_parking_slot_parking_lot_id'), 'dim_parking_slot', ['parking_lot_id'], unique=False)
    op.create_table('fact_occupancy',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_id', sa.Integer(), nullable=False),
    sa.Column('time_id', sa.Integer(), nullable=False),
    sa.Column('parking_lot_id', sa.Integer(), nullable=False),
    sa.Column('parking_slot_id', sa.Integer(), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_occupied', sa.Boolean(), nullable=False),
    sa.Column('is_reserved', sa.Boolean(), nullable=False),
    sa.Column('occupancy_confidence', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['date_id'], ['dim_date.id'], ),
    sa.ForeignKeyConstraint(['parking_lot_id'], ['dim_parking_lot.id'], ),
    sa.ForeignKeyConstraint(['parking_slot_id'], ['dim_parking_slot.id'], ),
    sa.ForeignKeyConstraint(['time_id'], ['dim_time.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('parking_slot_id', 'observed_at', name='uq_occupancy_slot_timestamp')
    )
    op.create_index(op.f('ix_fact_occupancy_date_id'), 'fact_occupancy', ['date_id'], unique=False)
    op.create_index(op.f('ix_fact_occupancy_observed_at'), 'fact_occupancy', ['observed_at'], unique=False)
    op.create_index(op.f('ix_fact_occupancy_parking_lot_id'), 'fact_occupancy', ['parking_lot_id'], unique=False)
    op.create_index(op.f('ix_fact_occupancy_parking_slot_id'), 'fact_occupancy', ['parking_slot_id'], unique=False)
    op.create_index(op.f('ix_fact_occupancy_time_id'), 'fact_occupancy', ['time_id'], unique=False)
    op.create_table('fact_reservation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_reservation_id', sa.Integer(), nullable=False),
    sa.Column('date_id', sa.Integer(), nullable=False),
    sa.Column('time_id', sa.Integer(), nullable=False),
    sa.Column('parking_lot_id', sa.Integer(), nullable=False),
    sa.Column('parking_slot_id', sa.Integer(), nullable=False),
    sa.Column('vehicle_type_id', sa.Integer(), nullable=True),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['date_id'], ['dim_date.id'], ),
    sa.ForeignKeyConstraint(['parking_lot_id'], ['dim_parking_lot.id'], ),
    sa.ForeignKeyConstraint(['parking_slot_id'], ['dim_parking_slot.id'], ),
    sa.ForeignKeyConstraint(['time_id'], ['dim_time.id'], ),
    sa.ForeignKeyConstraint(['vehicle_type_id'], ['dim_vehicle_type.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_reservation_id')
    )
    op.create_index(op.f('ix_fact_reservation_date_id'), 'fact_reservation', ['date_id'], unique=False)
    op.create_index(op.f('ix_fact_reservation_end_time'), 'fact_reservation', ['end_time'], unique=False)
    op.create_index(op.f('ix_fact_reservation_parking_lot_id'), 'fact_reservation', ['parking_lot_id'], unique=False)
    op.create_index(op.f('ix_fact_reservation_parking_slot_id'), 'fact_reservation', ['parking_slot_id'], unique=False)
    op.create_index(op.f('ix_fact_reservation_start_time'), 'fact_reservation', ['start_time'], unique=False)
    op.create_index(op.f('ix_fact_reservation_status'), 'fact_reservation', ['status'], unique=False)
    op.create_index(op.f('ix_fact_reservation_time_id'), 'fact_reservation', ['time_id'], unique=False)
    op.create_index(op.f('ix_fact_reservation_vehicle_type_id'), 'fact_reservation', ['vehicle_type_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fact_reservation_vehicle_type_id'), table_name='fact_reservation')
    op.drop_index(op.f('ix_fact_reservation_time_id'), table_name='fact_reservation')
    op.drop_index(op.f('ix_fact_reservation_status'), table_name='fact_reservation')
    op.drop_index(op.f('ix_fact_reservation_start_time'), table_name='fact_reservation')
    op.drop_index(op.f('ix_fact_reservation_parking_slot_id'), table_name='fact_reservation')
    op.drop_index(op.f('ix_fact_reservation_parking_lot_id'), table_name='fact_reservation')
    op.drop_index(op.f('ix_fact_reservation_end_time'), table_name='fact_reservation')
    op.drop_index(op.f('ix_fact_reservation_date_id'), table_name='fact_reservation')
    op.drop_table('fact_reservation')
    op.drop_index(op.f('ix_fact_occupancy_time_id'), table_name='fact_occupancy')
    op.drop_index(op.f('ix_fact_occupancy_parking_slot_id'), table_name='fact_occupancy')
    op.drop_index(op.f('ix_fact_occupancy_parking_lot_id'), table_name='fact_occupancy')
    op.drop_index(op.f('ix_fact_occupancy_observed_at'), table_name='fact_occupancy')
    op.drop_index(op.f('ix_fact_occupancy_date_id'), table_name='fact_occupancy')
    op.drop_table('fact_occupancy')
    op.drop_index(op.f('ix_dim_parking_slot_parking_lot_id'), table_name='dim_parking_slot')
    op.drop_table('dim_parking_slot')
    op.drop_table('dim_vehicle_type')
    op.drop_table('dim_time')
    op.drop_table('dim_parking_lot')
    op.drop_table('dim_date')
    # ### end Alembic commands ###
